name: Super-Linter

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  lint-python:
    name: Lint Python (black + isort)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run isort
        run: isort .
      - name: Run black
        run: black .

  super-linter:
    name: Run GitHub Super-Linter
    runs-on: ubuntu-latest
    needs: lint-python  # optional: run after `lint-python`, or remove to run in parallel
    steps:
      - uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
